### ISSUE TITLE
Enable Elements associated with maps to be added to data groups

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#154]
## Description
Currently it is possible to add a marker/line/poly from a data group to a map. 
It would be great to enable the converse of this as well - to add a drawn marker/line/poly to a data groups.

This is linked to #123 in that both issues have the same solution - to use the same UI for drawn/map element as for data layer markers.

## Acceptance Criteria
- WIth the same UI for the box on drawn/map elements the + symbol will open to a list of all Data Groups the current user is a 'moderator' of (we only have one user type right now, moderator, but I'm going to start using this language... for kicks.... or something)
- If the drawn marker is saved in a map, then the + symbol opens a '**Copy** Marker to' and the user can select from a list of 'My Data Groups'
- If the drawn marker is not saved then the + symbol opens a '**Save** Marker to' and the user can select from a list of 'My Data Groups' or 'My Maps'
- Additionally for completeness, if the marker is saved in a _data group_, then the + symbol opens a '**Copy** Marker to' and the user can select from a list of 'My Maps'

@rogup I know Mel has quite a lot on her plate at the moment, so do you think you can do this without a design? Feel free to share a screenshot for feedback so we can tweak before you complete the PR if that helps you

**Comment by rogup** [comment]
### Responses to questions:

- Does a map element need to be saved to a map first to do this? Should it?
  - No, we could just make a copy of the element as we do in the other direction
- If not, should drawn elements that are not yet saved to maps or data layers have the option to save to both?
  - I'd say we don't need to do this, since the element can be saved to the map later, as usual? And if we're moving towards auto-save, this UX would soon become obsolete anyway.
- If so we'll need to have a section for My Maps and a section for My Data Groups..... Otherwise any marker will already be in one of the two groups.
  - We don't currently have markers being in both a map AND a datagroup, since we decided against this and make copies instead (relating a bit to the discussion back in #117).
- Do we want to be able to save any marker to other maps and other data groups at the same time?
  - Yeah this sounds useful and wouldn't be too hard. It would need the two sections in the UI, as you described above. Do you think we should make it more obvious that we are copying the element, rather than adding the same one, so that the user knows that editing one of them won't affect oher copies?
  
@lin-d-hop what are your thoughts?

**Comment by lin-d-hop** [comment]
Thanks @rogup very helpful answers that align well with what we discussed in the meeting :)

I like your question about 'making is more obvious that we are copying the element'. I think this makes sense.

Would it be possible to:
- If the marker is only a drawn marker give the option to Save to -> My Maps |&| My Data Groups as described.
- If the marker is already in a data group OR a map then give the option to Copy to -> My Maps |OR| My Data groups (depending on which one its not already in).
??

This would mean a slight change of the boxes in every case. Is that reasonable to include in scope for this issue?

II'll update the issue to capture what you've said here @rogup :raised_hands:

**Comment by rogup** [comment]
@lin-d-hop Thanks. I think all of that is doable in this issue, and I can have a go without a design.

For the second bullet point, I was actually thinking that we could still have both My Maps |&| My Data Groups, if we wanted to copy a saved marker from one map to another map (or one datagroup to another datagroup). Do you think this would be useful? It wouldn't be difficult from a BE perspective, and would probably actually be simpler on the FE to avoid different UX cases.

**Comment by lin-d-hop** [comment]
@rogup Yes that makes sense. Agreed :) Good idea!

**Comment by lin-d-hop** [comment]
Hi @rogup 
Just checking in on this one as I'd love to get back to users awaiting it soon. How's it coming along?

**Comment by rogup** [comment]
@lin-d-hop @King-Mob Ready for review, sorry about the delay

**Comment by lin-d-hop** [comment]
@King-Mob @rogup Last meeting we spoke about this being the priority and it hasn't moved. I really need to get this in the next release and I can't even test it yet. Please can we put this to number one... I'm expecting testing might reveal some need to back and forth.

**Comment by lin-d-hop** [comment]
Heya @rogup
I'm not sure what's happened but it seems that currently the data layers aren't displaying correctly which, it seems, is completely blocking my ability to test this.

I've recorded a [loom](https://www.loom.com/share/fa349e1a87e5430895a56ad00e373789) with a little more detail.

Summary:
- I tried with my login and the testing account
- In neither account could I see any of the data group layers
- There was not an option on the marker to add to a data group layer, which is the correct behaviour if no data group layers are available to the user. However the users I tried should have.
- I check the DB and all the data groups, memberships and data were correctly set up still.

Hopefully it's just something little that got mixed up. But after all this what a shame to still not be able to test anything.

**Comment by rogup** [comment]
Ah it's because on the staging server, the FE branch was on '174-new-menu' instead of development so the changes didn't get picked up.

I'm not sure what that branch was being used for but I've moved it back to development. Sorry about that, should be ready now.

**Comment by lin-d-hop** [comment]
Still missing the data group layers (my account and testing account)

![Screenshot from 2023-02-01 23-34-37](https://user-images.githubusercontent.com/8669848/216191929-c760f2de-9b77-490d-9dad-2bd06b73f746.png)

**Comment by rogup** [comment]
Confused because I'm seeing the datagroups on my end on app.testing-lx.com (which I wasn't before switching branches)...

Please could you send a screenshot of the network tab in Chrome DevTools? Is there an API call that's failing?

**Comment by lin-d-hop** [comment]
![Screenshot from 2023-02-01 23-45-17](https://user-images.githubusercontent.com/8669848/216193367-5d6f7b0d-d396-44ad-bcdb-2c646f1f19c0.png)

**Comment by lin-d-hop** [comment]
> Is there an API call that's failing?

Looks like it:
Request URL: https://app.testing-lx.com/api/api/userdatagroups
Request Method: GET
Status Code: 404 Not Found

**Comment by rogup** [comment]
That's an old API call that is now user/datagroups. For some reason you're getting an old version of the FE site but I'm getting the updated version that I deployed 17 mins ago.

Are you able to try clearing your browser cache or try on a different browser?

**Comment by lin-d-hop** [comment]
Cool, yep that worked. Thanks @rogup

**Comment by lin-d-hop** [comment]
Hrm still having issues....
I can turn on and off the data group layer toggles.... but no data appears.

https://user-images.githubusercontent.com/8669848/216198162-ea580dac-08d9-43b6-893a-c15bd97f4442.mp4

**Comment by rogup** [comment]
Sorry, merge conflict which is now fixed

**Comment by lin-d-hop** [comment]
Alright dived into testing this:

1. Markers, lines and polys can all be added to existing data groups and maps :tada: 
2. Confirmed that adding to groups persists without map saving
3. Confirmed logging in with another user who has access to the same data groups
4. Confirmed share map works with the markers added as expected

This looks good to me. Very exciting features.

Next steps to future issues:
- Delete
- Redesign of the Maps and Layers tabs in the pop up
